"""add_regulation_marks_config

Revision ID: 012cfaa78467
Revises: 0337cb7a4bd8
Create Date: 2026-01-06 22:42:07.085652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '012cfaa78467'
down_revision: Union[str, None] = '0337cb7a4bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulations', sa.Column('theory_max_marks', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('regulations', sa.Column('theory_internal_max', sa.Integer(), nullable=False, server_default='60'))
    op.add_column('regulations', sa.Column('theory_external_max', sa.Integer(), nullable=False, server_default='40'))
    op.add_column('regulations', sa.Column('theory_pass_percentage', sa.Integer(), nullable=False, server_default='40'))
    op.add_column('regulations', sa.Column('practical_max_marks', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('regulations', sa.Column('practical_internal_max', sa.Integer(), nullable=False, server_default='40'))
    op.add_column('regulations', sa.Column('practical_external_max', sa.Integer(), nullable=False, server_default='60'))
    op.add_column('regulations', sa.Column('practical_pass_percentage', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulations', 'practical_pass_percentage')
    op.drop_column('regulations', 'practical_external_max')
    op.drop_column('regulations', 'practical_internal_max')
    op.drop_column('regulations', 'practical_max_marks')
    op.drop_column('regulations', 'theory_pass_percentage')
    op.drop_column('regulations', 'theory_external_max')
    op.drop_column('regulations', 'theory_internal_max')
    op.drop_column('regulations', 'theory_max_marks')
    # ### end Alembic commands ###
