"""refactor_student_model_strict_academic_structure

Revision ID: 0337cb7a4bd8
Revises: b76b03066184
Create Date: 2026-01-06 14:27:26.382641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0337cb7a4bd8'
down_revision: Union[str, None] = 'b76b03066184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('program_year_id', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('batch_semester_id', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('practical_batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_batch_id'), 'student', ['batch_id'], unique=False)
    op.create_index(op.f('ix_student_batch_semester_id'), 'student', ['batch_semester_id'], unique=False)
    op.create_index(op.f('ix_student_practical_batch_id'), 'student', ['practical_batch_id'], unique=False)
    op.create_index(op.f('ix_student_program_year_id'), 'student', ['program_year_id'], unique=False)
    op.create_index(op.f('ix_student_section_id'), 'student', ['section_id'], unique=False)
    op.create_foreign_key(None, 'student', 'academic_batches', ['batch_id'], ['id'])
    op.create_foreign_key(None, 'student', 'batch_semesters', ['batch_semester_id'], ['id'])
    op.create_foreign_key(None, 'student', 'practical_batch', ['practical_batch_id'], ['id'])
    op.create_foreign_key(None, 'student', 'program_years', ['program_year_id'], ['id'])
    op.create_foreign_key(None, 'student', 'section', ['section_id'], ['id'])
    op.drop_column('student', 'current_semester')
    op.drop_column('student', 'current_year')
    op.drop_column('student', 'section')
    op.drop_column('student', 'batch')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('batch', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('current_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('current_semester', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_index(op.f('ix_student_section_id'), table_name='student')
    op.drop_index(op.f('ix_student_program_year_id'), table_name='student')
    op.drop_index(op.f('ix_student_practical_batch_id'), table_name='student')
    op.drop_index(op.f('ix_student_batch_semester_id'), table_name='student')
    op.drop_index(op.f('ix_student_batch_id'), table_name='student')
    op.drop_column('student', 'practical_batch_id')
    op.drop_column('student', 'section_id')
    op.drop_column('student', 'batch_semester_id')
    op.drop_column('student', 'program_year_id')
    op.drop_column('student', 'batch_id')
    # ### end Alembic commands ###
