"""Add Student Import Module Tables

Revision ID: 074c6a62ff84
Revises: a6ea56dd72fc
Create Date: 2025-12-23 13:21:31.488218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '074c6a62ff84'
down_revision: Union[str, None] = 'a6ea56dd72fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('current_semester', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('student', sa.Column('batch', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('student', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False))
    op.add_column('student', sa.Column('aadhaar_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgroup'), nullable=True))
    op.add_column('student', sa.Column('hostel_required', sa.Boolean(), nullable=False))
    op.add_column('student', sa.Column('transport_required', sa.Boolean(), nullable=False))
    op.add_column('student', sa.Column('scholarship_category', sa.Enum('GENERAL', 'SC', 'ST', 'OBC', 'EWS', name='scholarshipcategory'), nullable=False))
    op.add_column('student', sa.Column('lateral_entry', sa.Boolean(), nullable=False))
    op.add_column('student', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ALUMNI', 'IMPORTED_PENDING_VERIFICATION', name='studentstatus'), nullable=False))
    op.create_index(op.f('ix_student_aadhaar_number'), 'student', ['aadhaar_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_aadhaar_number'), table_name='student')
    op.drop_column('student', 'status')
    op.drop_column('student', 'lateral_entry')
    op.drop_column('student', 'scholarship_category')
    op.drop_column('student', 'transport_required')
    op.drop_column('student', 'hostel_required')
    op.drop_column('student', 'blood_group')
    op.drop_column('student', 'aadhaar_number')
    op.drop_column('student', 'gender')
    op.drop_column('student', 'batch')
    op.drop_column('student', 'section')
    op.drop_column('student', 'current_semester')
    # ### end Alembic commands ###
