"""add_lesson_and_question_bank

Revision ID: 8a3595e31667
Revises: 761bd968a957
Create Date: 2025-12-25 18:42:54.755803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a3595e31667'
down_revision: Union[str, None] = '761bd968a957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_hours_planned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plan_academic_year'), 'lesson_plan', ['academic_year'], unique=False)
    op.create_index(op.f('ix_lesson_plan_faculty_id'), 'lesson_plan', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_subject_id'), 'lesson_plan', ['subject_id'], unique=False)
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_subject_id'), 'question_bank', ['subject_id'], unique=False)
    op.create_table('syllabus_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_plan_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='topicstatus'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_topic_lesson_plan_id'), 'syllabus_topic', ['lesson_plan_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('MCQ', 'THEORETICAL', 'PRACTICAL', name='questiontype'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('answer_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['syllabus_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_id'), 'question', ['bank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_bank_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_syllabus_topic_lesson_plan_id'), table_name='syllabus_topic')
    op.drop_table('syllabus_topic')
    op.drop_index(op.f('ix_question_bank_subject_id'), table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_index(op.f('ix_lesson_plan_subject_id'), table_name='lesson_plan')
    op.drop_index(op.f('ix_lesson_plan_faculty_id'), table_name='lesson_plan')
    op.drop_index(op.f('ix_lesson_plan_academic_year'), table_name='lesson_plan')
    op.drop_table('lesson_plan')
    # ### end Alembic commands ###
