"""extend_admissions_module_with_documents_and_activity_logs

Revision ID: 97c69a66ea17
Revises: d1f2e3a4b5c6
Create Date: 2025-12-26 13:02:49.803507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97c69a66ea17'
down_revision: Union[str, None] = 'd1f2e3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicationactivitylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('APPLICATION_CREATED', 'PAYMENT_INITIATED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'OFFLINE_PAYMENT_VERIFIED', 'FORM_COMPLETED', 'DOCUMENT_UPLOADED', 'DOCUMENT_VERIFIED', 'DOCUMENT_REJECTED', 'STATUS_CHANGED', 'ADMISSION_CONFIRMED', 'ADMISSION_REJECTED', name='activitytype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicationactivitylog_application_id'), 'applicationactivitylog', ['application_id'], unique=False)
    op.create_table('applicationdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PHOTO', 'AADHAAR', 'TENTH_MARKSHEET', 'TWELFTH_MARKSHEET', 'MIGRATION_CERTIFICATE', 'TRANSFER_CERTIFICATE', 'CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'VERIFIED', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicationdocument_application_id'), 'applicationdocument', ['application_id'], unique=False)
    op.drop_table('institute_info')
    op.add_column('application', sa.Column('fee_mode', sa.Enum('ONLINE', 'OFFLINE', name='feemode'), nullable=False))
    op.add_column('application', sa.Column('payment_proof_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('application', sa.Column('offline_payment_verified', sa.Boolean(), nullable=False))
    op.add_column('application', sa.Column('offline_payment_verified_by', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('offline_payment_verified_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'application', 'user', ['offline_payment_verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'offline_payment_verified_at')
    op.drop_column('application', 'offline_payment_verified_by')
    op.drop_column('application', 'offline_payment_verified')
    op.drop_column('application', 'payment_proof_url')
    op.drop_column('application', 'fee_mode')
    op.create_table('institute_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('short_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('logo_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_applicationdocument_application_id'), table_name='applicationdocument')
    op.drop_table('applicationdocument')
    op.drop_index(op.f('ix_applicationactivitylog_application_id'), table_name='applicationactivitylog')
    op.drop_table('applicationactivitylog')
    # ### end Alembic commands ###
