"""add_admissions_module_tables

Revision ID: 9cbff76e24e3
Revises: daa0aa1f2d1b
Create Date: 2025-12-25 16:49:38.927424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '9cbff76e24e3'
down_revision: Union[str, None] = 'daa0aa1f2d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_of_study', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aadhaar_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('previous_marks_percentage', sa.Float(), nullable=True),
    sa.Column('applied_for_scholarship', sa.Boolean(), nullable=False),
    sa.Column('hostel_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAYMENT_FAILED', 'PAID', 'FORM_COMPLETED', 'UNDER_REVIEW', 'APPROVED', 'ADMITTED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_aadhaar_number'), 'application', ['aadhaar_number'], unique=False)
    op.create_index(op.f('ix_application_application_number'), 'application', ['application_number'], unique=True)
    op.create_index(op.f('ix_application_email'), 'application', ['email'], unique=False)
    op.create_index(op.f('ix_application_phone'), 'application', ['phone'], unique=False)
    op.create_index(op.f('ix_application_program_id'), 'application', ['program_id'], unique=False)
    op.create_index(op.f('ix_application_status'), 'application', ['status'], unique=False)
    op.create_index(op.f('ix_application_student_id'), 'application', ['student_id'], unique=False)
    op.create_table('applicationpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='applicationpaymentstatus'), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicationpayment_application_id'), 'applicationpayment', ['application_id'], unique=False)
    op.create_index(op.f('ix_applicationpayment_transaction_id'), 'applicationpayment', ['transaction_id'], unique=True)
    op.create_table('entranceexamscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entranceexamscore_application_id'), 'entranceexamscore', ['application_id'], unique=True)
    op.alter_column('classadjustment', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED', name='adjustmentstatus'),
               existing_nullable=False)
    op.alter_column('exam', 'exam_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('MID_TERM', 'FINAL', 'INTERNAL', 'PRACTICAL', name='examtype'),
               existing_nullable=False)
    op.alter_column('exam', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'COMPLETED', name='examstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    op.alter_column('fee_component', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_constraint('fee_component_ibfk_1', 'fee_component', type_='foreignkey')
    op.create_foreign_key(None, 'fee_component', 'fee_structure', ['fee_structure_id'], ['id'])
    op.alter_column('fee_concession', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_constraint('fee_concession_ibfk_1', 'fee_concession', type_='foreignkey')
    op.create_foreign_key(None, 'fee_concession', 'student_fee', ['student_fee_id'], ['id'])
    op.alter_column('fee_fine', 'fine_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_constraint('fee_fine_ibfk_1', 'fee_fine', type_='foreignkey')
    op.create_foreign_key(None, 'fee_fine', 'student_fee', ['student_fee_id'], ['id'])
    op.alter_column('fee_installment', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_constraint('fee_installment_ibfk_1', 'fee_installment', type_='foreignkey')
    op.create_foreign_key(None, 'fee_installment', 'fee_structure', ['fee_structure_id'], ['id'])
    op.alter_column('fee_payment', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_constraint('fee_payment_ibfk_1', 'fee_payment', type_='foreignkey')
    op.create_foreign_key(None, 'fee_payment', 'student_fee', ['student_fee_id'], ['id'])
    op.alter_column('fee_structure', 'total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('maintenanceticket', 'priority',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'),
               existing_nullable=False)
    op.alter_column('maintenanceticket', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_parent_father_mobile'), 'parent', ['father_mobile'], unique=False)
    op.alter_column('student_fee', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('student_fee', 'concession_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('student_fee', 'fine_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('student_fee', 'paid_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('timeslot', 'type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('THEORY', 'PRACTICAL', 'BREAK', 'ASSEMBLY', name='slottype'),
               existing_nullable=False)
    op.alter_column('timetable_entry', 'day_of_week',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable_entry', 'day_of_week',
               existing_type=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('timeslot', 'type',
               existing_type=sa.Enum('THEORY', 'PRACTICAL', 'BREAK', 'ASSEMBLY', name='slottype'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('student_fee', 'paid_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('student_fee', 'fine_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('student_fee', 'concession_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('student_fee', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_parent_father_mobile'), table_name='parent')
    op.alter_column('maintenanceticket', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('maintenanceticket', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fee_structure', 'total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'fee_payment', type_='foreignkey')
    op.create_foreign_key('fee_payment_ibfk_1', 'fee_payment', 'student_fee', ['student_fee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fee_payment', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'fee_installment', type_='foreignkey')
    op.create_foreign_key('fee_installment_ibfk_1', 'fee_installment', 'fee_structure', ['fee_structure_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fee_installment', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'fee_fine', type_='foreignkey')
    op.create_foreign_key('fee_fine_ibfk_1', 'fee_fine', 'student_fee', ['student_fee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fee_fine', 'fine_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'fee_concession', type_='foreignkey')
    op.create_foreign_key('fee_concession_ibfk_1', 'fee_concession', 'student_fee', ['student_fee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fee_concession', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'fee_component', type_='foreignkey')
    op.create_foreign_key('fee_component_ibfk_1', 'fee_component', 'fee_structure', ['fee_structure_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fee_component', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('exam', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'COMPLETED', name='examstatus'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    op.alter_column('exam', 'exam_type',
               existing_type=sa.Enum('MID_TERM', 'FINAL', 'INTERNAL', 'PRACTICAL', name='examtype'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('classadjustment', 'status',
               existing_type=sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED', name='adjustmentstatus'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_entranceexamscore_application_id'), table_name='entranceexamscore')
    op.drop_table('entranceexamscore')
    op.drop_index(op.f('ix_applicationpayment_transaction_id'), table_name='applicationpayment')
    op.drop_index(op.f('ix_applicationpayment_application_id'), table_name='applicationpayment')
    op.drop_table('applicationpayment')
    op.drop_index(op.f('ix_application_student_id'), table_name='application')
    op.drop_index(op.f('ix_application_status'), table_name='application')
    op.drop_index(op.f('ix_application_program_id'), table_name='application')
    op.drop_index(op.f('ix_application_phone'), table_name='application')
    op.drop_index(op.f('ix_application_email'), table_name='application')
    op.drop_index(op.f('ix_application_application_number'), table_name='application')
    op.drop_index(op.f('ix_application_aadhaar_number'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
