"""add_odc_billing_payout_feedback

Revision ID: a6ea56dd72fc
Revises: c871debfff8e
Create Date: 2025-12-11 11:05:43.764790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6ea56dd72fc'
down_revision: Union[str, None] = 'c871debfff8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odc_billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('amount_per_student', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'CANCELLED', name='billingstatus'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'UPI', 'CHEQUE', name='paymentmethod'), nullable=True),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['odc_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_odc_billing_invoice_number'), 'odc_billing', ['invoice_number'], unique=True)
    op.create_table('odc_payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'UPI', 'CHEQUE', name='paymentmethod'), nullable=False),
    sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payout_date', sa.Date(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('processed_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['student_odc_application.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.add_column('student_odc_application', sa.Column('student_rating', sa.Integer(), nullable=True))
    op.add_column('student_odc_application', sa.Column('hotel_rating', sa.Integer(), nullable=True))
    op.add_column('student_odc_application', sa.Column('payout_amount', sa.Float(), nullable=True))
    op.add_column('student_odc_application', sa.Column('attendance_confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_odc_application', 'attendance_confirmed_at')
    op.drop_column('student_odc_application', 'payout_amount')
    op.drop_column('student_odc_application', 'hotel_rating')
    op.drop_column('student_odc_application', 'student_rating')
    op.drop_table('odc_payout')
    op.drop_index(op.f('ix_odc_billing_invoice_number'), table_name='odc_billing')
    op.drop_table('odc_billing')
    # ### end Alembic commands ###
