"""rename_program_year_to_year_no_batch_semester

Revision ID: b76b03066184
Revises: drop_legacy_tables
Create Date: 2026-01-06 12:31:32.050876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b76b03066184'
down_revision: Union[str, None] = 'drop_legacy_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance_session', 'program_years', ['program_year_id'], ['id'])
    op.add_column('batch_semesters', sa.Column('year_no', sa.Integer(), nullable=False))
    op.add_column('exam', sa.Column('batch_semester_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exam', 'batch_semesters', ['batch_semester_id'], ['id'])
    op.drop_column('exam', 'semester_id')
    op.add_column('timetable_entry', sa.Column('batch_semester_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'timetable_entry', 'batch_semesters', ['batch_semester_id'], ['id'])
    op.drop_column('timetable_entry', 'semester_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_entry', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timetable_entry', type_='foreignkey')
    op.drop_column('timetable_entry', 'batch_semester_id')
    op.add_column('exam', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'batch_semester_id')
    op.drop_column('batch_semesters', 'year_no')
    op.drop_constraint(None, 'attendance_session', type_='foreignkey')
    # ### end Alembic commands ###
