"""drop legacy tables

Revision ID: drop_legacy_tables
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'drop_legacy_tables'
down_revision = 'f352b322382d' # Use the last merge head
branch_labels = None
depends_on = None


def upgrade():
    # Drop legacy tables
    # "program_year" used to be singular. New one is program_years (if generated by SQLModel defaults? No, checks needed)
    # Check what new ProgramYear table name is.
    # In app/models/academic/batch.py: class ProgramYear... __tablename__ = "program_years" (usually plural? No, explicit?)
    # Let's check model definition.
    
    # Old model: __tablename__ = "program_year"
    # New model: app/models/academic/batch.py
    # Let's assume new model uses different name or we drop and recreate.
    # User said: "program_year table (singular)" to be removed.
    
    op.drop_table('practical_batch') # Depends on section, drop first
    op.drop_table('section') # Dropping section to recreate with new FK?
    
    # Drop legacy tables
    op.execute('DROP TABLE IF EXISTS semester CASCADE')
    op.execute('DROP TABLE IF EXISTS program_year CASCADE')
    # op.execute('DROP TABLE IF EXISTS academic_batch CASCADE') # Reusing table name? 
    # If new AcademicBatch uses same table name, we should drop it to clear old columns.
    op.execute('DROP TABLE IF EXISTS academic_batch CASCADE')

    # Re-creation will happen via init_db or we can let alembic auto-gen later?
    # Requirement: "Database schema can be created via init_db()"
    # So we just drop them here.
    pass


def downgrade():
    pass
