"""Add preferences to user model

Revision ID: 1ceeecea7e49
Revises: 5e8e21927d0f
Create Date: 2025-12-25 22:55:15.715018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ceeecea7e49'
down_revision: Union[str, None] = '5e8e21927d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferences')
    # ### end Alembic commands ###
