"""academic_structure_refactor

Revision ID: 28640fc3b7ee
Revises: 5ab8a5e08b39
Create Date: 2026-01-21 20:33:10.261053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28640fc3b7ee'
down_revision: Union[str, None] = '5ab8a5e08b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_practical_batch_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('practical_batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_semester_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_semester_id'], ['batch_semesters.id'], ),
    sa.ForeignKeyConstraint(['practical_batch_id'], ['practical_batch.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'batch_semester_id', name='uq_student_subject_allocation')
    )
    op.create_index(op.f('ix_student_practical_batch_allocation_batch_semester_id'), 'student_practical_batch_allocation', ['batch_semester_id'], unique=False)
    op.create_index(op.f('ix_student_practical_batch_allocation_practical_batch_id'), 'student_practical_batch_allocation', ['practical_batch_id'], unique=False)
    op.create_index(op.f('ix_student_practical_batch_allocation_student_id'), 'student_practical_batch_allocation', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_practical_batch_allocation_subject_id'), 'student_practical_batch_allocation', ['subject_id'], unique=False)
    op.add_column('attendance_session', sa.Column('practical_batch_id', sa.Integer(), nullable=True))
    op.alter_column('attendance_session', 'section',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_foreign_key(None, 'attendance_session', 'practical_batch', ['practical_batch_id'], ['id'])
    op.add_column('practical_batch', sa.Column('batch_semester_id', sa.Integer(), nullable=False))
    op.drop_index('ix_practical_batch_section_id', table_name='practical_batch')
    op.create_index(op.f('ix_practical_batch_batch_semester_id'), 'practical_batch', ['batch_semester_id'], unique=False)
    op.drop_constraint('practical_batch_section_id_fkey', 'practical_batch', type_='foreignkey')
    op.create_foreign_key(None, 'practical_batch', 'batch_semesters', ['batch_semester_id'], ['id'])
    op.drop_column('practical_batch', 'section_id')
    op.add_column('timetable_entry', sa.Column('practical_batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timetable_entry', 'practical_batch', ['practical_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable_entry', type_='foreignkey')
    op.drop_column('timetable_entry', 'practical_batch_id')
    op.add_column('practical_batch', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'practical_batch', type_='foreignkey')
    op.create_foreign_key('practical_batch_section_id_fkey', 'practical_batch', 'section', ['section_id'], ['id'])
    op.drop_index(op.f('ix_practical_batch_batch_semester_id'), table_name='practical_batch')
    op.create_index('ix_practical_batch_section_id', 'practical_batch', ['section_id'], unique=False)
    op.drop_column('practical_batch', 'batch_semester_id')
    op.drop_constraint(None, 'attendance_session', type_='foreignkey')
    op.alter_column('attendance_session', 'section',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('attendance_session', 'practical_batch_id')
    op.drop_index(op.f('ix_student_practical_batch_allocation_subject_id'), table_name='student_practical_batch_allocation')
    op.drop_index(op.f('ix_student_practical_batch_allocation_student_id'), table_name='student_practical_batch_allocation')
    op.drop_index(op.f('ix_student_practical_batch_allocation_practical_batch_id'), table_name='student_practical_batch_allocation')
    op.drop_index(op.f('ix_student_practical_batch_allocation_batch_semester_id'), table_name='student_practical_batch_allocation')
    op.drop_table('student_practical_batch_allocation')
    # ### end Alembic commands ###
