"""add hardening fields to academic batch

Revision ID: 2b31379810e3
Revises: 50261ff7edb1
Create Date: 2026-02-06 11:09:51.044158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b31379810e3'
down_revision: Union[str, None] = '50261ff7edb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_batches', sa.Column('regulation_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('academic_batches', sa.Column('frozen_at', sa.DateTime(), nullable=True))
    op.add_column('academic_batches', sa.Column('frozen_by_id', sa.Integer(), nullable=True))
    op.add_column('academic_batches', sa.Column('freeze_checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_foreign_key(None, 'academic_batches', 'users', ['frozen_by_id'], ['id'])
    op.add_column('batch_semesters', sa.Column('total_credits', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('batch_semesters', sa.Column('min_credits', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('batch_subjects', sa.Column('credits', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('batch_subjects', sa.Column('subject_type', sa.Enum('THEORY', 'PRACTICAL', 'PROJECT', 'ELECTIVE', 'AUDIT', name='subjecttype'), nullable=False, server_default='THEORY'))
    op.add_column('batch_subjects', sa.Column('evaluation_type', sa.Enum('THEORY_ONLY', 'PRACTICAL_ONLY', 'THEORY_AND_PRACTICAL', 'PROJECT', name='evaluationtype'), nullable=False, server_default='THEORY_ONLY'))
    op.add_column('batch_subjects', sa.Column('max_marks', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('batch_subjects', sa.Column('internal_max', sa.Integer(), nullable=False, server_default='40'))
    op.add_column('batch_subjects', sa.Column('external_max', sa.Integer(), nullable=False, server_default='60'))
    op.add_column('batch_subjects', sa.Column('counts_for_hall_ticket', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('batch_subjects', sa.Column('counts_for_promotion', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('regulation_subject', sa.Column('counts_for_hall_ticket', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('regulation_subject', sa.Column('counts_for_promotion', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('regulations', sa.Column('regulation_version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default='v1'))
    op.add_column('regulations', sa.Column('is_deprecated', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('regulations', sa.Column('effective_from_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulations', 'effective_from_year')
    op.drop_column('regulations', 'is_deprecated')
    op.drop_column('regulations', 'regulation_version')
    op.drop_column('regulation_subject', 'counts_for_promotion')
    op.drop_column('regulation_subject', 'counts_for_hall_ticket')
    op.drop_column('batch_subjects', 'counts_for_promotion')
    op.drop_column('batch_subjects', 'counts_for_hall_ticket')
    op.drop_column('batch_subjects', 'external_max')
    op.drop_column('batch_subjects', 'internal_max')
    op.drop_column('batch_subjects', 'max_marks')
    op.drop_column('batch_subjects', 'evaluation_type')
    op.drop_column('batch_subjects', 'subject_type')
    op.drop_column('batch_subjects', 'credits')
    op.drop_column('batch_semesters', 'min_credits')
    op.drop_column('batch_semesters', 'total_credits')
    op.drop_constraint(None, 'academic_batches', type_='foreignkey')
    op.drop_column('academic_batches', 'freeze_checksum')
    op.drop_column('academic_batches', 'frozen_by_id')
    op.drop_column('academic_batches', 'frozen_at')
    op.drop_column('academic_batches', 'regulation_code')
    # ### end Alembic commands ###
