"""add_strict_fields_to_program

Revision ID: 3662506e5c44
Revises: a99e9a300942
Create Date: 2026-02-06 12:43:44.651620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3662506e5c44'
down_revision: Union[str, None] = 'a99e9a300942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('semester_system', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('program', sa.Column('rnet_required', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('program', sa.Column('allow_installments', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'allow_installments')
    op.drop_column('program', 'rnet_required')
    op.drop_column('program', 'semester_system')
    # ### end Alembic commands ###
