"""rename academic_year name to year

Revision ID: 4456b75017f6
Revises: 2b31379810e3
Create Date: 2026-02-06 11:58:15.786089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4456b75017f6'
down_revision: Union[str, None] = '2b31379810e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_year', 'name', new_column_name='year')
    op.drop_index('ix_academic_year_name', table_name='academic_year')
    op.create_index(op.f('ix_academic_year_year'), 'academic_year', ['year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_year', 'year', new_column_name='name')
    op.drop_index(op.f('ix_academic_year_year'), table_name='academic_year')
    op.create_index('ix_academic_year_name', 'academic_year', ['name'], unique=True)
    # ### end Alembic commands ###
