"""Add department_id to Subject and Application

Revision ID: 50261ff7edb1
Revises: a477ec86d732
Create Date: 2026-02-05 18:28:16.948746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50261ff7edb1'
down_revision: Union[str, None] = 'a477ec86d732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_application_department_id'), 'application', ['department_id'], unique=False)
    op.create_foreign_key(None, 'application', 'department', ['department_id'], ['id'])
    op.add_column('department', sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('department', sa.Column('department_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('department', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('department', sa.Column('hod_faculty_id', sa.Integer(), nullable=True))
    op.drop_index('ix_department_code', table_name='department')
    op.drop_index('ix_department_name', table_name='department')
    op.create_index(op.f('ix_department_department_code'), 'department', ['department_code'], unique=True)
    op.create_index(op.f('ix_department_department_name'), 'department', ['department_name'], unique=True)
    op.create_index(op.f('ix_department_hod_faculty_id'), 'department', ['hod_faculty_id'], unique=False)
    op.drop_column('department', 'alias')
    op.drop_column('department', 'name')
    op.drop_column('department', 'code')
    op.drop_column('department', 'updated_at')
    op.add_column('program', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'program', 'department', ['department_id'], ['id'])
    op.add_column('subject', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'department', ['department_id'], ['id'])
    op.drop_column('system_import_log', 'failed_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_import_log', sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'department_id')
    op.drop_constraint(None, 'program', type_='foreignkey')
    op.drop_column('program', 'department_id')
    op.add_column('department', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('department', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('department', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('department', sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_department_hod_faculty_id'), table_name='department')
    op.drop_index(op.f('ix_department_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_department_code'), table_name='department')
    op.create_index('ix_department_name', 'department', ['name'], unique=True)
    op.create_index('ix_department_code', 'department', ['code'], unique=True)
    op.drop_column('department', 'hod_faculty_id')
    op.drop_column('department', 'description')
    op.drop_column('department', 'department_code')
    op.drop_column('department', 'department_name')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_index(op.f('ix_application_department_id'), table_name='application')
    op.drop_column('application', 'department_id')
    # ### end Alembic commands ###
