"""Add fee_head_id to FeeComponent

Revision ID: 5ab8a5e08b39
Revises: eaf09857f36f
Create Date: 2026-01-18 21:29:21.245277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ab8a5e08b39'
down_revision: Union[str, None] = 'eaf09857f36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_component', sa.Column('fee_head_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fee_component_fee_head_id'), 'fee_component', ['fee_head_id'], unique=False)
    op.create_foreign_key(None, 'fee_component', 'fee_head', ['fee_head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee_component', type_='foreignkey')
    op.drop_index(op.f('ix_fee_component_fee_head_id'), table_name='fee_component')
    op.drop_column('fee_component', 'fee_head_id')
    # ### end Alembic commands ###
