"""add_regulation_system

Revision ID: 5e4c401dd090
Revises: bc72602bca65
Create Date: 2026-01-05 22:34:02.473234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e4c401dd090'
down_revision: Union[str, None] = 'bc72602bca65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('import_log')  # Commented out - table doesn't exist
    # op.drop_index('ix_file_metadata_entity_id', table_name='file_metadata')
    # op.drop_index('ix_file_metadata_entity_type', table_name='file_metadata')
    # op.drop_index('ix_file_metadata_file_key', table_name='file_metadata')
    # op.drop_index('ix_file_metadata_module', table_name='file_metadata')
    # op.drop_index('ix_file_metadata_uploaded_at', table_name='file_metadata')
    # op.drop_table('file_metadata')  # Commented out - table doesn't exist
    op.alter_column('program', 'short_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('program', 'semester_system',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('program', 'rnet_required',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('program', 'allow_installments',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('program_year', 'program_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('idx_program_year_academic_batch', table_name='program_year')
    op.drop_column('program_year', 'academic_batch_id')
    op.drop_column('program_year', 'end_date')
    op.drop_column('program_year', 'start_date')
    op.alter_column('section', 'semester_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('idx_section_program_year_id', table_name='section')
    op.drop_constraint('fk_section_program_year', 'section', type_='foreignkey')
    op.drop_column('section', 'program_year_id')
    op.add_column('semester', sa.Column('start_month', sa.Integer(), nullable=True))
    op.add_column('semester', sa.Column('end_month', sa.Integer(), nullable=True))
    op.alter_column('semester', 'start_date',
               existing_type=sa.DATE(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('semester', 'end_date',
               existing_type=sa.DATE(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('subject', 'semester_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('idx_subject_program', table_name='subject')
    op.drop_column('subject', 'program_year')
    op.drop_column('subject', 'subject_type')
    op.drop_column('subject', 'is_active')
    op.drop_column('subject', 'hours_per_session')
    op.drop_column('subject', 'program_id')
    op.drop_column('subject', 'passing_percentage')
    op.drop_column('subject', 'has_exam')
    op.drop_column('subject', 'mid_exam_marks')
    op.drop_column('subject', 'short_name')
    op.drop_column('subject', 'max_marks')
    op.drop_column('subject', 'has_assignments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('has_assignments', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('max_marks', mysql.INTEGER(display_width=11), server_default=sa.text('100'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('short_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('subject', sa.Column('mid_exam_marks', mysql.INTEGER(display_width=11), server_default=sa.text('30'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('has_exam', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('passing_percentage', mysql.INTEGER(display_width=11), server_default=sa.text('40'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('program_id', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('hours_per_session', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('subject_type', mysql.VARCHAR(length=20), server_default=sa.text("'THEORY'"), nullable=True))
    op.add_column('subject', sa.Column('program_year', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_index('idx_subject_program', 'subject', ['program_id'], unique=False)
    op.alter_column('subject', 'semester_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('semester', 'end_date',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('semester', 'start_date',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('semester', 'end_month')
    op.drop_column('semester', 'start_month')
    op.add_column('section', sa.Column('program_year_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_section_program_year', 'section', 'program_year', ['program_year_id'], ['id'])
    op.create_index('idx_section_program_year_id', 'section', ['program_year_id'], unique=False)
    op.alter_column('section', 'semester_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('program_year', sa.Column('start_date', sa.DATE(), nullable=True))
    op.add_column('program_year', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('program_year', sa.Column('academic_batch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('idx_program_year_academic_batch', 'program_year', ['academic_batch_id'], unique=False)
    op.alter_column('program_year', 'program_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('program', 'allow_installments',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('program', 'rnet_required',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('program', 'semester_system',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('program', 'short_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.create_table('file_metadata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('file_key', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('bucket_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('checksum', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('module', mysql.ENUM('ADMISSIONS', 'STUDENTS', 'FACULTY', 'EXAMS', 'LIBRARY', 'HOSTEL', 'FEES', 'COMMUNICATION', 'INSTITUTE', 'OTHER'), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name='file_metadata_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_file_metadata_uploaded_at', 'file_metadata', ['uploaded_at'], unique=False)
    op.create_index('ix_file_metadata_module', 'file_metadata', ['module'], unique=False)
    op.create_index('ix_file_metadata_file_key', 'file_metadata', ['file_key'], unique=True)
    op.create_index('ix_file_metadata_entity_type', 'file_metadata', ['entity_type'], unique=False)
    op.create_index('ix_file_metadata_entity_id', 'file_metadata', ['entity_id'], unique=False)
    op.create_table('import_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uploaded_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('total_rows', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('imported_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('failed_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('duplicate_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('module', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('error_report_path', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], name='import_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
