"""add_import_log_and_parent_tables

Revision ID: 5e6d0f6b2957
Revises: 074c6a62ff84
Create Date: 2025-12-24 11:52:40.510247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e6d0f6b2957'
down_revision: Union[str, None] = '074c6a62ff84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_report_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_student_id', sa.Integer(), nullable=False),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('father_mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mother_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['linked_student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_father_mobile'), 'parent', ['father_mobile'], unique=False)
    op.create_index(op.f('ix_parent_linked_student_id'), 'parent', ['linked_student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_linked_student_id'), table_name='parent')
    op.drop_index(op.f('ix_parent_father_mobile'), table_name='parent')
    op.drop_table('parent')
    op.drop_table('import_log')
    # ### end Alembic commands ###
