"""add_inventory_tables

Revision ID: 8a6da3e4fc8c
Revises: 8a3595e31667
Create Date: 2025-12-25 19:33:35.008710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a6da3e4fc8c'
down_revision: Union[str, None] = '8a3595e31667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('UNIFORM', 'IT_EQUIPMENT', 'LAB_EQUIPMENT', 'FURNITURE', 'STATIONERY', 'OTHERS', name='assetcategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_stock', sa.Integer(), nullable=False),
    sa.Column('available_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_category'), 'asset', ['category'], unique=False)
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=False)
    op.create_index(op.f('ix_asset_qr_code'), 'asset', ['qr_code'], unique=True)
    op.create_table('asset_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.Column('expected_stock', sa.Integer(), nullable=False),
    sa.Column('actual_stock', sa.Integer(), nullable=False),
    sa.Column('variance', sa.Integer(), nullable=False),
    sa.Column('audited_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_audit_asset_id'), 'asset_audit', ['asset_id'], unique=False)
    op.create_table('asset_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('performed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_maintenance_asset_id'), 'asset_maintenance', ['asset_id'], unique=False)
    op.create_table('asset_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ISSUED', 'RETURNED', 'DAMAGED', 'LOST', name='allocationstatus'), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_allocation_asset_id'), 'asset_allocation', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_allocation_faculty_id'), 'asset_allocation', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_asset_allocation_student_id'), 'asset_allocation', ['student_id'], unique=False)
    op.create_table('uniform_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'CUSTOM', name='uniformsize'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uniform_allocation_student_id'), 'uniform_allocation', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uniform_allocation_student_id'), table_name='uniform_allocation')
    op.drop_table('uniform_allocation')
    op.drop_index(op.f('ix_asset_allocation_student_id'), table_name='asset_allocation')
    op.drop_index(op.f('ix_asset_allocation_faculty_id'), table_name='asset_allocation')
    op.drop_index(op.f('ix_asset_allocation_asset_id'), table_name='asset_allocation')
    op.drop_table('asset_allocation')
    op.drop_index(op.f('ix_asset_maintenance_asset_id'), table_name='asset_maintenance')
    op.drop_table('asset_maintenance')
    op.drop_index(op.f('ix_asset_audit_asset_id'), table_name='asset_audit')
    op.drop_table('asset_audit')
    op.drop_index(op.f('ix_asset_qr_code'), table_name='asset')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_index(op.f('ix_asset_category'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
