"""Add LOGGED_IN to ApplicationStatus enum

Revision ID: 93572dec5727
Revises: b475a44e2aea
Create Date: 2026-01-26 13:45:28.100669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93572dec5727'
down_revision: Union[str, None] = 'b475a44e2aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Enum Update
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE applicationstatus ADD VALUE IF NOT EXISTS 'LOGGED_IN'")
        op.execute("ALTER TYPE applicationstatus ADD VALUE IF NOT EXISTS 'FORM_IN_PROGRESS'")

    op.alter_column('application', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'application', 'user', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.alter_column('application', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
