"""add_comprehensive_application_details

Revision ID: a477ec86d732
Revises: 93572dec5727
Create Date: 2026-02-04 21:21:35.614705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a477ec86d732'
down_revision: Union[str, None] = '93572dec5727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('address_type', postgresql.ENUM('PRESENT', 'PERMANENT', 'COMMUNICATION', name='addresstype', create_type=False), nullable=False),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('village_city', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('telephone_residence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telephone_office', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_address_application_id'), 'application_address', ['application_id'], unique=False)
    op.create_table('application_bank_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('account_holder_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('ifsc_code', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_bank_details_application_id'), 'application_bank_details', ['application_id'], unique=True)
    # Manual Enum Value Additions
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'CONDUCT_CERTIFICATE'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'BONAFIDE_CERTIFICATE'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'EQUIVALENCY_CERTIFICATE'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'MEDICAL_FITNESS_CERTIFICATE'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'STUDENT_SIGNATURE'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'PARENT_SIGNATURE'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'ADDRESS_PROOF'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'SPORTS_CERTIFICATE'")
        op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'NCC_CERTIFICATE'")

    op.create_table('application_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', postgresql.ENUM('PHOTO', 'AADHAAR', 'TENTH_MARKSHEET', 'TWELFTH_MARKSHEET', 'MIGRATION_CERTIFICATE', 'TRANSFER_CERTIFICATE', 'CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'CONDUCT_CERTIFICATE', 'BONAFIDE_CERTIFICATE', 'EQUIVALENCY_CERTIFICATE', 'MEDICAL_FITNESS_CERTIFICATE', 'STUDENT_SIGNATURE', 'PARENT_SIGNATURE', 'ADDRESS_PROOF', 'SPORTS_CERTIFICATE', 'NCC_CERTIFICATE', 'OTHER', name='documenttype', create_type=False), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('UPLOADED', 'VERIFIED', 'REJECTED', name='documentstatus', create_type=False), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_document_application_id'), 'application_document', ['application_id'], unique=False)
    op.create_table('application_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('level', postgresql.ENUM('SSC', 'INTERMEDIATE', 'DIPLOMA', 'DEGREE', 'POST_GRADUATE', name='educationlevel'), nullable=False),
    sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('institution_address', sa.Text(), nullable=True),
    sa.Column('institution_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('board', postgresql.ENUM('CBSE', 'ICSE', 'STATE_BOARD', 'IB', 'NIOS', 'UNIVERSITY', 'OTHER', name='educationboard'), nullable=False),
    sa.Column('board_other', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('hall_ticket_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('year_of_passing', sa.Integer(), nullable=True),
    sa.Column('secured_marks', sa.Float(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_education_application_id'), 'application_education', ['application_id'], unique=False)
    op.create_table('application_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('relation', postgresql.ENUM('FATHER', 'MOTHER', 'GUARDIAN', 'GRANDFATHER', 'GRANDMOTHER', 'UNCLE', 'AUNT', 'SIBLING', 'OTHER', name='parentrelation'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender', create_type=False), nullable=True),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qualification', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_ifsc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_parent_application_id'), 'application_parent', ['application_id'], unique=False)
    op.create_table('application_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('is_medically_fit', sa.Boolean(), nullable=False),
    sa.Column('practitioner_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('practitioner_registration_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('certificate_date', sa.Date(), nullable=True),
    sa.Column('certificate_place', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('certificate_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['certificate_document_id'], ['application_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_health_application_id'), 'application_health', ['application_id'], unique=True)
    op.drop_index('ix_applicationdocument_application_id', table_name='applicationdocument')
    op.drop_table('applicationdocument')
    
    # Manually create types for add_column operations
    op.execute("CREATE TYPE religion AS ENUM ('HINDU', 'MUSLIM', 'CHRISTIAN', 'SIKH', 'BUDDHIST', 'JAIN', 'PARSI', 'OTHER', 'PREFER_NOT_TO_SAY')")
    op.execute("CREATE TYPE castecategory AS ENUM ('GENERAL', 'OC', 'BC_A', 'BC_B', 'BC_C', 'BC_D', 'BC_E', 'SC', 'ST', 'EWS')")
    op.execute("CREATE TYPE activitylevel AS ENUM ('COLLEGE', 'DISTRICT', 'STATE', 'NATIONAL', 'INTERNATIONAL')")

    op.add_column('application', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('blood_group', postgresql.ENUM('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgroup', create_type=False), nullable=True))
    op.add_column('application', sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('application', sa.Column('religion', postgresql.ENUM('HINDU', 'MUSLIM', 'CHRISTIAN', 'SIKH', 'BUDDHIST', 'JAIN', 'PARSI', 'OTHER', 'PREFER_NOT_TO_SAY', name='religion'), nullable=True))
    op.add_column('application', sa.Column('caste_category', postgresql.ENUM('GENERAL', 'OC', 'BC_A', 'BC_B', 'BC_C', 'BC_D', 'BC_E', 'SC', 'ST', 'EWS', name='castecategory'), nullable=True))
    op.add_column('application', sa.Column('identification_mark_1', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('application', sa.Column('identification_mark_2', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('application', sa.Column('ssc_hall_ticket', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('application', sa.Column('medium_of_study', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('application', sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('application', sa.Column('native_place', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('application', sa.Column('native_state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('application', sa.Column('extra_curricular_activities', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('application', sa.Column('activity_level', postgresql.ENUM('COLLEGE', 'DISTRICT', 'STATE', 'NATIONAL', 'INTERNATIONAL', name='activitylevel'), nullable=True))
    op.add_column('application', sa.Column('activity_sponsored_by', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('application', sa.Column('hobbies', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('application', sa.Column('student_declaration_accepted', sa.Boolean(), nullable=False))
    op.add_column('application', sa.Column('parent_declaration_accepted', sa.Boolean(), nullable=False))
    op.add_column('application', sa.Column('declaration_date', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('declaration_place', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'declaration_place')
    op.drop_column('application', 'declaration_date')
    op.drop_column('application', 'parent_declaration_accepted')
    op.drop_column('application', 'student_declaration_accepted')
    op.drop_column('application', 'hobbies')
    op.drop_column('application', 'activity_sponsored_by')
    op.drop_column('application', 'activity_level')
    op.drop_column('application', 'extra_curricular_activities')
    op.drop_column('application', 'native_state')
    op.drop_column('application', 'native_place')
    op.drop_column('application', 'place_of_birth')
    op.drop_column('application', 'medium_of_study')
    op.drop_column('application', 'ssc_hall_ticket')
    op.drop_column('application', 'identification_mark_2')
    op.drop_column('application', 'identification_mark_1')
    op.drop_column('application', 'caste_category')
    op.drop_column('application', 'religion')
    op.drop_column('application', 'nationality')
    op.drop_column('application', 'blood_group')
    op.drop_column('application', 'date_of_birth')
    op.create_table('applicationdocument',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('PHOTO', 'AADHAAR', 'TENTH_MARKSHEET', 'TWELFTH_MARKSHEET', 'MIGRATION_CERTIFICATE', 'TRANSFER_CERTIFICATE', 'CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'OTHER', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('UPLOADED', 'VERIFIED', 'REJECTED', name='documentstatus'), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name='applicationdocument_application_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='applicationdocument_verified_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='applicationdocument_pkey')
    )
    op.create_index('ix_applicationdocument_application_id', 'applicationdocument', ['application_id'], unique=False)
    op.drop_index(op.f('ix_application_health_application_id'), table_name='application_health')
    op.drop_table('application_health')
    op.drop_index(op.f('ix_application_parent_application_id'), table_name='application_parent')
    op.drop_table('application_parent')
    op.drop_index(op.f('ix_application_education_application_id'), table_name='application_education')
    op.drop_table('application_education')
    op.drop_index(op.f('ix_application_document_application_id'), table_name='application_document')
    op.drop_table('application_document')
    op.drop_index(op.f('ix_application_bank_details_application_id'), table_name='application_bank_details')
    op.drop_table('application_bank_details')
    op.drop_index(op.f('ix_application_address_application_id'), table_name='application_address')
    op.drop_table('application_address')
    # ### end Alembic commands ###
