"""align academic batch model with schema fields

Revision ID: a99e9a300942
Revises: 4456b75017f6
Create Date: 2026-02-06 12:02:26.373674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a99e9a300942'
down_revision: Union[str, None] = '4456b75017f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_batches', 'name', new_column_name='batch_name')
    op.add_column('academic_batches', sa.Column('batch_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='TEMP-CODE'))
    op.add_column('academic_batches', sa.Column('joining_year', sa.Integer(), nullable=False, server_default='2024'))
    op.add_column('academic_batches', sa.Column('start_year', sa.Integer(), nullable=False, server_default='2024'))
    op.add_column('academic_batches', sa.Column('end_year', sa.Integer(), nullable=False, server_default='2028'))
    op.add_column('academic_batches', sa.Column('total_students', sa.Integer(), nullable=False, server_default='0'))
    
    # Optional: Update batch_code from batch_name to avoid unique constraint violations
    op.execute("UPDATE academic_batches SET batch_code = batch_name WHERE batch_code = 'TEMP-CODE'")
    
    op.drop_index('ix_academic_batches_name', table_name='academic_batches')
    op.create_index(op.f('ix_academic_batches_batch_code'), 'academic_batches', ['batch_code'], unique=True)
    op.create_index(op.f('ix_academic_batches_batch_name'), 'academic_batches', ['batch_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_batches', 'batch_name', new_column_name='name')
    op.drop_index(op.f('ix_academic_batches_batch_name'), table_name='academic_batches')
    op.drop_index(op.f('ix_academic_batches_batch_code'), table_name='academic_batches')
    op.create_index('ix_academic_batches_name', 'academic_batches', ['name'], unique=True)
    op.drop_column('academic_batches', 'total_students')
    op.drop_column('academic_batches', 'end_year')
    op.drop_column('academic_batches', 'start_year')
    op.drop_column('academic_batches', 'joining_year')
    op.drop_column('academic_batches', 'batch_code')
    # ### end Alembic commands ###
