"""add fee management tables

Revision ID: b8f3c4d5e6a7
Revises: a6ea56dd72fc
Create Date: 2025-12-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8f3c4d5e6a7'
down_revision: Union[str, None] = '074c6a62ff84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'MANAGEMENT', 'NRI', 'SCHOLARSHIP', name='feecategory'), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structure_academic_year'), 'fee_structure', ['academic_year'], unique=False)
    op.create_index(op.f('ix_fee_structure_program_id'), 'fee_structure', ['program_id'], unique=False)
    
    op.create_table('fee_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_refundable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_component_fee_structure_id'), 'fee_component', ['fee_structure_id'], unique=False)
    
    op.create_table('fee_installment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_installment_fee_structure_id'), 'fee_installment', ['fee_structure_id'], unique=False)
    
    op.create_table('student_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('concession_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fine_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fee_academic_year'), 'student_fee', ['academic_year'], unique=False)
    op.create_index(op.f('ix_student_fee_fee_structure_id'), 'student_fee', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_student_fee_student_id'), 'student_fee', ['student_id'], unique=False)
    
    op.create_table('fee_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_fee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('ONLINE', 'CASH', 'CHEQUE', 'DD', 'UPI', name='paymentmode'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gateway_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payment_student_fee_id'), 'fee_payment', ['student_fee_id'], unique=False)
    op.create_index(op.f('ix_fee_payment_transaction_id'), 'fee_payment', ['transaction_id'], unique=False)
    
    op.create_table('fee_concession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_fee_id', sa.Integer(), nullable=False),
    sa.Column('concession_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_concession_student_fee_id'), 'fee_concession', ['student_fee_id'], unique=False)
    
    op.create_table('fee_fine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_fee_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('fine_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waived', sa.Boolean(), nullable=False),
    sa.Column('waived_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('waived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_fine_student_fee_id'), 'fee_fine', ['student_fee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_fine_student_fee_id'), table_name='fee_fine')
    op.drop_table('fee_fine')
    op.drop_index(op.f('ix_fee_concession_student_fee_id'), table_name='fee_concession')
    op.drop_table('fee_concession')
    op.drop_index(op.f('ix_fee_payment_transaction_id'), table_name='fee_payment')
    op.drop_index(op.f('ix_fee_payment_student_fee_id'), table_name='fee_payment')
    op.drop_table('fee_payment')
    op.drop_index(op.f('ix_student_fee_student_id'), table_name='student_fee')
    op.drop_index(op.f('ix_student_fee_fee_structure_id'), table_name='student_fee')
    op.drop_index(op.f('ix_student_fee_academic_year'), table_name='student_fee')
    op.drop_table('student_fee')
    op.drop_index(op.f('ix_fee_installment_fee_structure_id'), table_name='fee_installment')
    op.drop_table('fee_installment')
    op.drop_index(op.f('ix_fee_component_fee_structure_id'), table_name='fee_component')
    op.drop_table('fee_component')
    op.drop_index(op.f('ix_fee_structure_program_id'), table_name='fee_structure')
    op.drop_index(op.f('ix_fee_structure_academic_year'), table_name='fee_structure')
    op.drop_table('fee_structure')
    # ### end Alembic commands ###
