"""Add rich program management fields fixed

Revision ID: bc72602bca65
Revises: 152e7eaf4071
Create Date: 2026-01-02 15:19:03.254806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc72602bca65'
down_revision: Union[str, None] = '152e7eaf4071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_metadata_entity', table_name='file_metadata')
    op.drop_index('ix_file_metadata_entity_id', table_name='file_metadata')
    op.drop_index('ix_file_metadata_entity_type', table_name='file_metadata')
    op.drop_index('ix_file_metadata_file_key', table_name='file_metadata')
    op.drop_index('ix_file_metadata_module', table_name='file_metadata')
    op.drop_index('ix_file_metadata_uploaded_at', table_name='file_metadata')
    op.drop_table('file_metadata')
    op.add_column('program', sa.Column('program_type', sa.Enum('UG', 'PG', 'DIPLOMA', 'CERTIFICATE', 'PHD', name='programtype'), nullable=False))
    op.add_column('program', sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='programstatus'), nullable=False))
    op.add_column('program', sa.Column('eligibility_criteria', sa.Text(), nullable=True))
    op.add_column('program', sa.Column('program_outcomes', sa.Text(), nullable=True))
    op.add_column('program', sa.Column('total_credits', sa.Integer(), nullable=False))
    op.add_column('program', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('program', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('program', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('program_year', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('semester', sa.Column('is_internship', sa.Boolean(), nullable=False))
    op.add_column('semester', sa.Column('is_project_semester', sa.Boolean(), nullable=False))
    op.add_column('semester', sa.Column('start_month', sa.Integer(), nullable=True))
    op.add_column('semester', sa.Column('end_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semester', 'end_month')
    op.drop_column('semester', 'start_month')
    op.drop_column('semester', 'is_project_semester')
    op.drop_column('semester', 'is_internship')
    op.drop_column('program_year', 'is_active')
    op.drop_column('program', 'updated_at')
    op.drop_column('program', 'created_at')
    op.drop_column('program', 'is_active')
    op.drop_column('program', 'total_credits')
    op.drop_column('program', 'program_outcomes')
    op.drop_column('program', 'eligibility_criteria')
    op.drop_column('program', 'status')
    op.drop_column('program', 'program_type')
    op.create_table('file_metadata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('file_key', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('bucket_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_size', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('checksum', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('module', mysql.ENUM('ADMISSIONS', 'STUDENTS', 'FACULTY', 'EXAMS', 'LIBRARY', 'HOSTEL', 'FEES', 'COMMUNICATION', 'INSTITUTE', 'OTHER'), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name='file_metadata_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_file_metadata_uploaded_at', 'file_metadata', ['uploaded_at'], unique=False)
    op.create_index('ix_file_metadata_module', 'file_metadata', ['module'], unique=False)
    op.create_index('ix_file_metadata_file_key', 'file_metadata', ['file_key'], unique=True)
    op.create_index('ix_file_metadata_entity_type', 'file_metadata', ['entity_type'], unique=False)
    op.create_index('ix_file_metadata_entity_id', 'file_metadata', ['entity_id'], unique=False)
    op.create_index('ix_file_metadata_entity', 'file_metadata', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###
