"""Add health biometrics and medical fields

Revision ID: be7357c596a9
Revises: f33333333333
Create Date: 2026-02-08 15:24:55.947901

"""
from typing import Sequence, Union
"""Add health biometrics and medical fields

Revision ID: be7357c596a9
Revises: f33333333333
Create Date: 2026-02-08 15:24:55.947901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'be7357c596a9'
down_revision: Union[str, None] = 'f33333333333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # [FIX] Update existing null values before setting NOT NULL
    op.execute("UPDATE application SET current_step = 1 WHERE current_step IS NULL")
    op.execute("UPDATE application SET last_saved_at = NOW() WHERE last_saved_at IS NULL")

    op.alter_column('application', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('application', 'last_saved_at',
               existing_type=sa.DateTime(), # Using standard sa.DateTime
               nullable=False)
    op.add_column('application_health', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('application_health', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('application_health', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('application_health', sa.Column('chronic_illness_details', sa.Text(), nullable=True))
    op.add_column('application_health', sa.Column('doctor_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('application_health', sa.Column('doctor_phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_health', 'doctor_phone')
    op.drop_column('application_health', 'doctor_name')
    op.drop_column('application_health', 'chronic_illness_details')
    op.drop_column('application_health', 'allergies')
    op.drop_column('application_health', 'weight_kg')
    op.drop_column('application_health', 'height_cm')
    op.alter_column('application', 'last_saved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('application', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
