"""add odc module and student user_id

Revision ID: c871debfff8e
Revises: 88680ea6d900
Create Date: 2025-12-11 01:57:41.392330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c871debfff8e'
down_revision: Union[str, None] = '88680ea6d900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odc_hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_pay_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odc_hotel_name'), 'odc_hotel', ['name'], unique=False)
    op.create_table('odc_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('report_time', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('gender_preference', sa.Enum('MALE', 'FEMALE', 'ANY', name='genderpreference'), nullable=False),
    sa.Column('pay_amount', sa.Float(), nullable=False),
    sa.Column('transport_provided', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'COMPLETED', 'CANCELLED', name='odcstatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['odc_hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_odc_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SELECTED', 'REJECTED', 'ATTENDED', 'ABSENT', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('admin_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('student_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hotel_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payout_status', sa.Enum('PENDING', 'PAID', name='payoutstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['odc_request.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_user_id'), 'student', ['user_id'], unique=False)
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_index(op.f('ix_student_user_id'), table_name='student')
    op.drop_column('student', 'user_id')
    op.drop_table('student_odc_application')
    op.drop_table('odc_request')
    op.drop_index(op.f('ix_odc_hotel_name'), table_name='odc_hotel')
    op.drop_table('odc_hotel')
    # ### end Alembic commands ###
