"""add_enhanced_admission_workflow_fields

Revision ID: c89173db1e83
Revises: 28640fc3b7ee
Create Date: 2026-01-22 08:00:39.154579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c89173db1e83'
down_revision: Union[str, None] = '28640fc3b7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('portal_user_id', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('portal_password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('application', sa.Column('portal_first_login', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('portal_last_login', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('quick_apply_completed_at', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('full_form_started_at', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('full_form_completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_application_portal_user_id'), 'application', ['portal_user_id'], unique=False)
    op.create_foreign_key(None, 'application', 'user', ['portal_user_id'], ['id'])
    op.alter_column('batch_semesters', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_semesters', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_index(op.f('ix_application_portal_user_id'), table_name='application')
    op.drop_column('application', 'full_form_completed_at')
    op.drop_column('application', 'full_form_started_at')
    op.drop_column('application', 'quick_apply_completed_at')
    op.drop_column('application', 'portal_last_login')
    op.drop_column('application', 'portal_first_login')
    op.drop_column('application', 'portal_password_hash')
    op.drop_column('application', 'portal_user_id')
    # ### end Alembic commands ###
