"""Add academic_audit_log table and faculty_id to section

Revision ID: f01ba63fccbd
Revises: 012cfaa78467
Create Date: 2026-01-07 21:40:25.844464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f01ba63fccbd'
down_revision: Union[str, None] = '012cfaa78467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_section_faculty_id'), 'section', ['faculty_id'], unique=False)
    op.create_foreign_key(None, 'section', 'faculty', ['faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.drop_index(op.f('ix_section_faculty_id'), table_name='section')
    op.drop_column('section', 'faculty_id')
    # ### end Alembic commands ###
